<?php
/**
 * AdminBase.php
 * Created By Colorful
 * Date:2018/5/14
 * Time:下午7:17
 */
class AdminBaseController extends AbstractController
{

    public function init()
    {
        // parent::init(); // TODO: Change the autogenerated stub
    }


}
